### ISSUE TITLE
force update not working in 2.0.38

### ISSUE THREAD

**Issue by zadigre** [fuatakgun/kia_uvo#459]
Hyundai Kona Electric 2021, Canada. 
version 2.0.38

force update service not working... errors are in the log. 
it looks like it does receive the data in the log... but data is not parsed to the sensors. 
Downgraded to 2.0.37... problem is still present. (I didn't use force update with this version before).
Downgraded to 2.0.36... and it's working fine.
so it appears changes in 2.0.37 broke something. 

here's the log on 2.0.38
`2022-11-30 06:08:29.241 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Sign In Response {"responseHeader":{"responseCode":0,"responseDesc":"Success"},"result":{"accessToken":"eyJlbmMiOiJlR3BIMW9FWG51RDkveXBib05zYWpSMldrN2pNeDFFTTZlOUJlbG90YXF5NW9icWZXaDdTV0ZSWVcrRmNnSDlqSGRYWG1yUEhqL3pRZXN2ZW54c3orcXNwY2Y0WmMyU3ZXZkZRM1hScnl1a3JrZVdxSlJ1S09uSlE1VElocmVqL09OeU9YdllDanMwMDNwbmNOc0JMU2xTK0VFekZpTmdLZFpMSC9GbmdHOTlVNG95bEdHYkVqWXlOcXdMcWE2MTdkUzh0VklaWU40cnU4VkVldE11TkNTbFEwWVRXMVJOL1Q4SDhJNDJHQU5rVlcyN2R0b0E4UStySmZ6WVlzRi9lOTFQNlMzbkUxMWorbWRoZzU0U09Xbk9pM09LTWxoeDJCRjA0eDFtVnlvL1ZBN0l1TFIxdkR2UzdSS1ExSWRSeldyVXI3OERJZGhKSmNIYWRaUDZvSm41MkY2VUNkZU90NHoxM2ZpYnN5Umh2endDKzV0QWw0QVBOY2djWXNrMGI4dkh2M041VHN0bE9vS1lUbTVqaTFpVUlGcDljUzB5VXVabjZhcTUwT1dwSTVBZ1AxUDBHNkZrOWkveG41M0kyb2tpZkZyL2lvTlBHNVlCbTB2eHk5SktteVp0R3l2RmMxL3V5VTRtQ3RZK2JpK3MrMG5nbU1kcUYwV29WSm9BUW5DeTNKNEwwWjBiMElLczZJVERsK21aTWVsU0tOWWI1cTJiNDVJQndZeldvL2JFaVhhTE5vTTZTWVp0dXZDVDJyeUFPcGRtSUVwVGZtK3BHd2NWMERBYTdnN0kvT3VWbkllUnJ4MTl2SE1yNGlvVU91cnVpU2NhTEdGeDNPbURrM29HYzBkU2NYQmFpRE5GN0d4K3Fjb0dXTi9jZG53V3dWL2w2WmE1NTMxeXVoTGtZaGlwaHpWVVU1dWZOSlR6c2x2N3l4VDJzVmZKZ2xqbTRYcWpwQytHQVo0dWxVZVRadXRBTk1xM1lTdG9Gb25XTjh4SnY3b05RVFhoY2V0NXlaWm1waVUwdHlmNm9NSGsrUW1MeWdLM0laTytBM01oMHkwUHBCbEhxNVhPM3BTcXNHRzZMR2pJQnhmRzlkSjhSajhPOVJ1ODlENy9MVDdlQWZWODZxTmVYL2RyVkkxbXpFQkQ4RFdZN0MzeDJXd1hFYkFFNWptNTc4MEx4RjBVc0w2WlZKUFdKWUExaHFUQm9rc3RoNm1UVjBHNzhYL2JCUitVb2JjMWFyMm5kSzRqQjhqRHlGUEhJODd5N1NBeERwN3dXRlJia2ZGWFBhRjczZEFhekxpcUVXNjJMMjVTV1hEMHFtbzd1OTlTVDB1RFlJNGl2cklCOXpGdW1naE1sTlByZnNlK200ZmttbjZMSlRteEpXM2xkWXhJY1RsSm5qYm5nOHFpaGxCbz0iLCJrZXkiOiJJU281eGV5cVpUZ2xDWnQ2Y2oxelkydGtFaG0ySUgzblZpaEVYNTFqRjBMai8xWEd3OGtYM0ZUamp3M0pMcXFyMFI3VkoyTlhHU0RYalpBTzNRTWVKQT09In0=","scope":["profile"],"tokenType":"bearer","expireIn":86400,"refreshToken":"eyJlbmMiOiJ1dUhzR3RaYWNLdnBuTFFwdC9EL2FjRVVhWnBBekdnckMzaU1NdTRNZ0o1YmlubjBtMHlTUm90b1BlZlFpR0VzUTNGNHJaOUVQR2pVT1hEaUFSTlRMNFhiYVNHWmlnT1hHSlovZDBKUU9BM0NRVDdVUmt6L1RwS01EeTdubis5Ulh2L290ZjhHSVVLRmpnaUY4aVRjakRHQjYxRWFDc0V6YTVVd1pSYnlvcmNYeGxYaGl5MlVsQU1BZ0FKVGhqMXdoeS9kbmhtVCt3NGxmV3Q4NVEvZUZBZTgxZnd4R3lJd0plMHE1Rk43a0hIOHZUaEU5OEIzYzdiUURjZzBrSGU5WnkzRmgzSS8rMDNpVllScGRVNzVkU0ViRnBTZjlJTDRxZEFxS015SHFzVDd2bVB5bUxmYnoxWFlwcFpjWmlzSjh6YStwZU5MWHdNRzE1UGJPZW8vM3BMYm9QMFhSODdoc0c4MFcyODRNMlZmR0dGeXJwOExsdGorVUhYb3ZkZDN5VU1zT05QZXlnNUt4a1hmOTg2S1RoVVJlTy93eEJoTW9za1FwRWcwbnBxL1F3MXRCejllVTFWbms0em1DUjc3NTNKQllWeVNaM1RIZHUvSWM4RSt0NEo3MVdyYWh3Vm53RnNZTjRXL0RLdGZpRmsyb05ka0Nmc0twMGhqdStaNVQ4d3JZcW43K2xLNUhBNzZodnBvaUxrZGp1ZXA2NkNRNlpWUW16ZUZUUXNtdXkrYUF0MTJHSnBjSXlqQzNnUnd3bXMxTlY2TEVFRm05QlZyT2dqK0VYVUt4MVVkRnJFaUt0T24wN0NrcDI1eXUxZFpIK3ZnVTRTdEdNazdHaDRjUWNXNXVEOXE1VDlkYmpNTmllZ1ZrTGN1VEhMZlJKNVludnNIV3BUQ1d0bGdYdnVzY1pwQ1NueHE5dGtCc3NrQStPSExaQVpJMDI5ZjBEOWt4bkV1NEtlcGxESm9reWpHY0dERXZYT2ZFRlI3ZkNTczRseDBOdzZ4RkV0MEpiR0RwQ3dHNGhVQ3gvc2lZa0k5Umg2S1UwVHNrZDBPOFFrdytxa0Z5N3QwbHNwbjlUakhKcUNQV3ovajgxNEtkeGw2bHFMMWVhb2JsUzZWc2JjWUZIMmJ6ZSs4eC9ucXRUOGJLUy9BWG5xZHhNQU1Vbk9qelNDK213ZjF4UHVuT3JNTDFwSHdNdll5Tkp1bHlUWDQxSzdhTHo4eWdKemJ0VnNUeUs1U1gyVWVDQ1FubnBxTWxhVVdxaDhMYTFFL0Uxb255TUdIOS8rVUJwUk1VQ1JJTFZTcTg5ekkrMHJ1cU1jSS81TXZxU0Vaa1VjV1FuVnRHZExwT2RiRlc5M0pRb0xSUGx4THpXT1MwWTVNMUhId3huNm1kTXZrRXh5aldHNm1BMnpoSHl6bzJhMD0iLCJrZXkiOiJTN3ZvUUhmcHNhVVR2YzBMTkJ4dGNOTitVclpJV0lOUTQzOVZaVzdNUDhmck4zbjFsbWdFTndYZmlPK0JlbFJEMUxKN0U2UW9JYU80ZVdFcExLRnR3UT09In0=","signature":""}}
2022-11-30 06:08:29.241 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Access Token Value eyJlbmMiOiJlR3BIMW9FWG51RDkveXBib05zYWpSMldrN2pNeDFFTTZlOUJlbG90YXF5NW9icWZXaDdTV0ZSWVcrRmNnSDlqSGRYWG1yUEhqL3pRZXN2ZW54c3orcXNwY2Y0WmMyU3ZXZkZRM1hScnl1a3JrZVdxSlJ1S09uSlE1VElocmVqL09OeU9YdllDanMwMDNwbmNOc0JMU2xTK0VFekZpTmdLZFpMSC9GbmdHOTlVNG95bEdHYkVqWXlOcXdMcWE2MTdkUzh0VklaWU40cnU4VkVldE11TkNTbFEwWVRXMVJOL1Q4SDhJNDJHQU5rVlcyN2R0b0E4UStySmZ6WVlzRi9lOTFQNlMzbkUxMWorbWRoZzU0U09Xbk9pM09LTWxoeDJCRjA0eDFtVnlvL1ZBN0l1TFIxdkR2UzdSS1ExSWRSeldyVXI3OERJZGhKSmNIYWRaUDZvSm41MkY2VUNkZU90NHoxM2ZpYnN5Umh2endDKzV0QWw0QVBOY2djWXNrMGI4dkh2M041VHN0bE9vS1lUbTVqaTFpVUlGcDljUzB5VXVabjZhcTUwT1dwSTVBZ1AxUDBHNkZrOWkveG41M0kyb2tpZkZyL2lvTlBHNVlCbTB2eHk5SktteVp0R3l2RmMxL3V5VTRtQ3RZK2JpK3MrMG5nbU1kcUYwV29WSm9BUW5DeTNKNEwwWjBiMElLczZJVERsK21aTWVsU0tOWWI1cTJiNDVJQndZeldvL2JFaVhhTE5vTTZTWVp0dXZDVDJyeUFPcGRtSUVwVGZtK3BHd2NWMERBYTdnN0kvT3VWbkllUnJ4MTl2SE1yNGlvVU91cnVpU2NhTEdGeDNPbURrM29HYzBkU2NYQmFpRE5GN0d4K3Fjb0dXTi9jZG53V3dWL2w2WmE1NTMxeXVoTGtZaGlwaHpWVVU1dWZOSlR6c2x2N3l4VDJzVmZKZ2xqbTRYcWpwQytHQVo0dWxVZVRadXRBTk1xM1lTdG9Gb25XTjh4SnY3b05RVFhoY2V0NXlaWm1waVUwdHlmNm9NSGsrUW1MeWdLM0laTytBM01oMHkwUHBCbEhxNVhPM3BTcXNHRzZMR2pJQnhmRzlkSjhSajhPOVJ1ODlENy9MVDdlQWZWODZxTmVYL2RyVkkxbXpFQkQ4RFdZN0MzeDJXd1hFYkFFNWptNTc4MEx4RjBVc0w2WlZKUFdKWUExaHFUQm9rc3RoNm1UVjBHNzhYL2JCUitVb2JjMWFyMm5kSzRqQjhqRHlGUEhJODd5N1NBeERwN3dXRlJia2ZGWFBhRjczZEFhekxpcUVXNjJMMjVTV1hEMHFtbzd1OTlTVDB1RFlJNGl2cklCOXpGdW1naE1sTlByZnNlK200ZmttbjZMSlRteEpXM2xkWXhJY1RsSm5qYm5nOHFpaGxCbz0iLCJrZXkiOiJJU281eGV5cVpUZ2xDWnQ2Y2oxelkydGtFaG0ySUgzblZpaEVYNTFqRjBMai8xWEd3OGtYM0ZUamp3M0pMcXFyMFI3VkoyTlhHU0RYalpBTzNRTWVKQT09In0=
2022-11-30 06:08:29.241 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Refresh Token Value eyJlbmMiOiJ1dUhzR3RaYWNLdnBuTFFwdC9EL2FjRVVhWnBBekdnckMzaU1NdTRNZ0o1YmlubjBtMHlTUm90b1BlZlFpR0VzUTNGNHJaOUVQR2pVT1hEaUFSTlRMNFhiYVNHWmlnT1hHSlovZDBKUU9BM0NRVDdVUmt6L1RwS01EeTdubis5Ulh2L290ZjhHSVVLRmpnaUY4aVRjakRHQjYxRWFDc0V6YTVVd1pSYnlvcmNYeGxYaGl5MlVsQU1BZ0FKVGhqMXdoeS9kbmhtVCt3NGxmV3Q4NVEvZUZBZTgxZnd4R3lJd0plMHE1Rk43a0hIOHZUaEU5OEIzYzdiUURjZzBrSGU5WnkzRmgzSS8rMDNpVllScGRVNzVkU0ViRnBTZjlJTDRxZEFxS015SHFzVDd2bVB5bUxmYnoxWFlwcFpjWmlzSjh6YStwZU5MWHdNRzE1UGJPZW8vM3BMYm9QMFhSODdoc0c4MFcyODRNMlZmR0dGeXJwOExsdGorVUhYb3ZkZDN5VU1zT05QZXlnNUt4a1hmOTg2S1RoVVJlTy93eEJoTW9za1FwRWcwbnBxL1F3MXRCejllVTFWbms0em1DUjc3NTNKQllWeVNaM1RIZHUvSWM4RSt0NEo3MVdyYWh3Vm53RnNZTjRXL0RLdGZpRmsyb05ka0Nmc0twMGhqdStaNVQ4d3JZcW43K2xLNUhBNzZodnBvaUxrZGp1ZXA2NkNRNlpWUW16ZUZUUXNtdXkrYUF0MTJHSnBjSXlqQzNnUnd3bXMxTlY2TEVFRm05QlZyT2dqK0VYVUt4MVVkRnJFaUt0T24wN0NrcDI1eXUxZFpIK3ZnVTRTdEdNazdHaDRjUWNXNXVEOXE1VDlkYmpNTmllZ1ZrTGN1VEhMZlJKNVludnNIV3BUQ1d0bGdYdnVzY1pwQ1NueHE5dGtCc3NrQStPSExaQVpJMDI5ZjBEOWt4bkV1NEtlcGxESm9reWpHY0dERXZYT2ZFRlI3ZkNTczRseDBOdzZ4RkV0MEpiR0RwQ3dHNGhVQ3gvc2lZa0k5Umg2S1UwVHNrZDBPOFFrdytxa0Z5N3QwbHNwbjlUakhKcUNQV3ovajgxNEtkeGw2bHFMMWVhb2JsUzZWc2JjWUZIMmJ6ZSs4eC9ucXRUOGJLUy9BWG5xZHhNQU1Vbk9qelNDK213ZjF4UHVuT3JNTDFwSHdNdll5Tkp1bHlUWDQxSzdhTHo4eWdKemJ0VnNUeUs1U1gyVWVDQ1FubnBxTWxhVVdxaDhMYTFFL0Uxb255TUdIOS8rVUJwUk1VQ1JJTFZTcTg5ekkrMHJ1cU1jSS81TXZxU0Vaa1VjV1FuVnRHZExwT2RiRlc5M0pRb0xSUGx4THpXT1MwWTVNMUhId3huNm1kTXZrRXh5aldHNm1BMnpoSHl6bzJhMD0iLCJrZXkiOiJTN3ZvUUhmcHNhVVR2YzBMTkJ4dGNOTitVclpJV0lOUTQzOVZaVzdNUDhmck4zbjFsbWdFTndYZmlPK0JlbFJEMUxKN0U2UW9JYU80ZVdFcExLRnR3UT09In0=
2022-11-30 06:08:29.773 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Vehicles Response {"responseHeader":{"responseCode":0,"responseDesc":"Success"},"result":{"vehicles":[{"vehicleId":"qLHNk/TY2fGJeLL1FVGDXA==","nickName":"Kona VÉ","modelCode":"KE1SEFEMEX51","modelName":"KONA EV","modelYear":"2021","fuelKindCode":"E","trim":"Preferred Two-Tone","engine":"","exteriorColor":"Y21","dtcCount":0,"subscriptionStatus":"A","subscriptionEndDate":"20240715","mileageForNextService":5082.0,"daysForNextService":"20230219","overviewMessage":"","defaultVehicle":true,"enrollmentStatus":"4","genType":"G3","photoUrl":"https://mybluelink.ca/vin/2021/11/16418071120a4165b2d1c07528d9c3bb_1637173565996.jpeg","valetParkingModeOn":1,"vin":"KM8K23AG9MU124939"}]}}
2022-11-30 06:08:30.344 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20221130103328', 'airCtrlOn': False, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': '00H', 'unit': 0}, 'defrost': False, 'acc': False, 'evStatus': {'batteryCharge': False, 'batteryStatus': 76, 'batteryPlugin': 0, 'remainTime2': {'etc1': {'value': 0, 'unit': 1}, 'etc2': {'value': 0, 'unit': 1}, 'etc3': {'value': 0, 'unit': 1}, 'atc': {'value': 0, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'gasModeRange': {'value': 0.0, 'unit': 1}, 'evModeRange': {'value': 324.0, 'unit': 1}, 'totalAvailableRange': {'value': 324.0, 'unit': 1}}, 'type': 2}]}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'sideBackWindowHeat': 0, 'dte': {}, 'tirePressureLamp': {'tirePressureLampAll': 0}, 'battery': {'batSoc': 81, 'batState': 0, 'batSignalReferenceValue': {}}, 'remoteIgnition': True, 'seatHeaterVentInfo': {}, 'sleepModeCheck': False, 'lampWireStatus': {'headLamp': {}, 'stopLamp': {}, 'turnSignalLamp': {}}, 'windowOpen': {}, 'engineRuntime': {}}}}
2022-11-30 06:08:30.344 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Old Vehicle Last Updated: 0001-01-01 00:00:00
2022-11-30 06:08:30.345 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - before 20221130103328
2022-11-30 06:08:30.345 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - after 2022-11-30 10:33:28+00:00
2022-11-30 06:08:30.345 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Current Vehicle Last Updated: 2022-11-30 10:33:28+00:00
2022-11-30 06:08:30.840 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Service status data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'maintenanceInfo': {'msopServiceOdometer': 48081.0, 'msopServiceOdometerUnit': 1, 'mtspServiceDate': '20220819', 'imatServiceOdometer': 60081.0, 'imatServiceOdometerUnit': 1, 'mtitServiceDate': '20230219', 'currentOdometer': 54999.0, 'currentOdometerUnit': 1, 'serviceOdometerDuration': 12000.0, 'serviceDaysDuration': 184, 'serviceMonthsThreshold': 6}}}
2022-11-30 06:08:31.566 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received Pin validation response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'pAuth': 'tSwLKLKsAEgQjMMkWwlgFAOVukHZtfaA'}}
2022-11-30 06:08:35.455 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Vehicle Location {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'head': 211, 'coord': {'lat': 45.57989999, 'lon': -73.5163275, 'alt': 12.7, 'type': 0}, 'accuracy': {'hdop': 0, 'pdop': 1}, 'time': '20221130110833', 'speed': {'value': 0, 'unit': 0}}}
2022-11-30 06:08:36.116 DEBUG (SyncWorker_5) [hyundai_kia_connect_api.VehicleManager] hyundai_kia_connect_api - Time differential in seconds: 2108.116295
2022-11-30 06:08:36.850 DEBUG (SyncWorker_5) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20221130103328', 'airCtrlOn': False, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': '00H', 'unit': 0}, 'defrost': False, 'acc': False, 'evStatus': {'batteryCharge': False, 'batteryStatus': 76, 'batteryPlugin': 0, 'remainTime2': {'etc1': {'value': 0, 'unit': 1}, 'etc2': {'value': 0, 'unit': 1}, 'etc3': {'value': 0, 'unit': 1}, 'atc': {'value': 0, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'gasModeRange': {'value': 0.0, 'unit': 1}, 'evModeRange': {'value': 324.0, 'unit': 1}, 'totalAvailableRange': {'value': 324.0, 'unit': 1}}, 'type': 2}]}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'sideBackWindowHeat': 0, 'dte': {}, 'tirePressureLamp': {'tirePressureLampAll': 0}, 'battery': {'batSoc': 81, 'batState': 0, 'batSignalReferenceValue': {}}, 'remoteIgnition': True, 'seatHeaterVentInfo': {}, 'sleepModeCheck': False, 'lampWireStatus': {'headLamp': {}, 'stopLamp': {}, 'turnSignalLamp': {}}, 'windowOpen': {}, 'engineRuntime': {}}}}
2022-11-30 06:08:36.850 DEBUG (SyncWorker_5) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Old Vehicle Last Updated: 2022-11-30 10:33:28+00:00
2022-11-30 06:08:36.850 DEBUG (SyncWorker_5) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - before 20221130103328
2022-11-30 06:08:36.850 DEBUG (SyncWorker_5) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - after 2022-11-30 10:33:28+00:00
2022-11-30 06:08:36.851 DEBUG (SyncWorker_5) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Current Vehicle Last Updated: 2022-11-30 10:33:28+00:00
2022-11-30 06:08:37.467 DEBUG (SyncWorker_5) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Service status data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'maintenanceInfo': {'msopServiceOdometer': 48081.0, 'msopServiceOdometerUnit': 1, 'mtspServiceDate': '20220819', 'imatServiceOdometer': 60081.0, 'imatServiceOdometerUnit': 1, 'mtitServiceDate': '20230219', 'currentOdometer': 54999.0, 'currentOdometerUnit': 1, 'serviceOdometerDuration': 12000.0, 'serviceDaysDuration': 184, 'serviceMonthsThreshold': 6}}}
2022-11-30 06:08:38.139 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 9.879 seconds (success: True)
2022-11-30 06:08:38.229 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'temp' when rendering '{{ state_attr('sensor.meteo_kona', 'main')['temp'] }}'
2022-11-30 06:08:38.235 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'temp' when rendering '{{ state_attr('sensor.meteo_kona', 'main')['temp'] }}'
2022-11-30 06:09:21.435 DEBUG (SyncWorker_9) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received forced vehicle data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20221130110920', 'airCtrlOn': False, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': '00H', 'unit': 0}, 'defrost': False, 'acc': False, 'evStatus': {'batteryCharge': False, 'batteryStatus': 76, 'batteryPlugin': 0, 'remainTime2': {'etc1': {'value': 0, 'unit': 1}, 'etc2': {'value': 0, 'unit': 1}, 'etc3': {'value': 0, 'unit': 1}, 'atc': {'value': 0, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'gasModeRange': {'value': 0.0, 'unit': 1}, 'evModeRange': {'value': 324.0, 'unit': 1}, 'totalAvailableRange': {'value': 324.0, 'unit': 1}}, 'type': 2}]}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'sideBackWindowHeat': 0, 'dte': {}, 'tirePressureLamp': {'tirePressureLampAll': 0}, 'battery': {'batSoc': 81, 'batState': 0, 'batSignalReferenceValue': {}}, 'remoteIgnition': True, 'seatHeaterVentInfo': {}, 'sleepModeCheck': False, 'lampWireStatus': {'headLamp': {}, 'stopLamp': {}, 'turnSignalLamp': {}}, 'windowOpen': {}, 'engineRuntime': {}}}}
2022-11-30 06:09:21.437 ERROR (MainThread) [homeassistant.components.script.force_update_kona] KONA - Force update: Error executing script. Unexpected error for call_service at pos 1: 'KiaUvoApiCA' object has no attribute '_update_vehicle_properties'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/kia_uvo/services.py", line 45, in async_handle_force_update
await coordinator.async_force_update_all()
File "/config/custom_components/kia_uvo/coordinator.py", line 139, in async_force_update_all
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 84, in force_refresh_all_vehicles_states
self.force_refresh_vehicle_state(self.get_vehicle(vehicle_id))
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 87, in force_refresh_vehicle_state
self.api.force_refresh_vehicle_state(self.token, vehicle)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 142, in force_refresh_vehicle_state
self._update_vehicle_properties(vehicle, state)
AttributeError: 'KiaUvoApiCA' object has no attribute '_update_vehicle_properties'
2022-11-30 06:09:21.450 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 484, in _async_run
return await self.script.async_run(script_vars, context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/kia_uvo/services.py", line 45, in async_handle_force_update
await coordinator.async_force_update_all()
File "/config/custom_components/kia_uvo/coordinator.py", line 139, in async_force_update_all
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 84, in force_refresh_all_vehicles_states
self.force_refresh_vehicle_state(self.get_vehicle(vehicle_id))
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 87, in force_refresh_vehicle_state
self.api.force_refresh_vehicle_state(self.token, vehicle)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 142, in force_refresh_vehicle_state
self._update_vehicle_properties(vehicle, state)
AttributeError: 'KiaUvoApiCA' object has no attribute '_update_vehicle_properties'`

**Comment by cdnninja** [comment]
Put in the fix for that.  Next version will resolve it.  I will sift through a few of the other reports before I release.

**Comment by zadigre** [comment]
Confirmed working fine in 2.0.39
