### ISSUE TITLE
start/stop charge giving errors on 2.0.1

### ISSUE THREAD

**Issue by zadigre** [fuatakgun/kia_uvo#391]
Canada, Kona Electric 2.0.1

the start and stop charge services are giving error. I see an unknown error "popup" when starting the service from the dev tools menu and errors in the log.
This is on 2.0.1. was working fine with stable 1.8.x version.
both start and stop do the same. see below logs for start. 

2022-10-30 07:30:30.811 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'KiaUvoApiCA' object has no attribute 'get_pin_token'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/kia_uvo/services.py", line 82, in async_handle_start_charge
await coordinator.async_start_charge(vehicle_id)
File "/config/custom_components/kia_uvo/coordinator.py", line 127, in async_start_charge
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 112, in stop_charge
return self.api.stop_charge(self.token, self.get_vehicle(vehicle_id))
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 485, in stop_charge
headers["pAuth"] = self.get_pin_token(token, vehicle.id)
AttributeError: 'KiaUvoApiCA' object has no attribute 'get_pin_token'
2022-10-30 07:30:30.815 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140718001351616] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 648, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/kia_uvo/services.py", line 82, in async_handle_start_charge
await coordinator.async_start_charge(vehicle_id)
File "/config/custom_components/kia_uvo/coordinator.py", line 127, in async_start_charge
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 112, in stop_charge
return self.api.stop_charge(self.token, self.get_vehicle(vehicle_id))
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 485, in stop_charge
headers["pAuth"] = self.get_pin_token(token, vehicle.id)
AttributeError: 'KiaUvoApiCA' object has no attribute 'get_pin_token'

**Comment by cdnninja** [comment]
You are awesome! Thank you so much for helping test this new version.  Once we get back to feature parity this will really help the community push forward on new items like multi car.   By the time you read this the latest 2.0.X build should solve this error.  Working through the others still.

**Comment by cdnninja** [comment]
Fix is released.  Here is the commit: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/3d904c88236cb971051abfd144fe9ede4ce737a4

**Comment by zadigre** [comment]
2.0.2 was not showing as an update. 
I went to redownload... and selected 2.0.2. 
integration doesn't start now... and I get this in the log : 
2022-10-30 12:57:08.107 ERROR (MainThread) [homeassistant.config_entries] Migration handler not found for entry Hyundai Canada myemailaddress@here for kia_uvo

I redownloaded 2.0.1 and back to what it was before (working with the same previous errors).

**Comment by cdnninja** [comment]
Oops I released the 1.X branch as 2.0.2.  This has been fixed so 2.0.2 is actually the correct version.  As a note while chatting I believe climate start will still have issues.   I haven't had time to dig into that yet.  I can't test charge though since I have an ICE.

**Comment by zadigre** [comment]
not working... still has some errors in the log... but slightly different I believe. 

2022-10-30 14:24:13.467 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'str' object has no attribute 'id'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/kia_uvo/services.py", line 82, in async_handle_start_charge
await coordinator.async_start_charge(vehicle_id)
File "/config/custom_components/kia_uvo/coordinator.py", line 127, in async_start_charge
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 112, in stop_charge
return self.api.stop_charge(self.token, self.get_vehicle(vehicle_id))
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 485, in stop_charge
headers["pAuth"] = self._get_pin_token(token, vehicle.id)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 333, in _get_pin_token
headers["vehicleId"] = vehicle.id
AttributeError: 'str' object has no attribute 'id'
2022-10-30 14:24:13.475 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139851764809296] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 648, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/kia_uvo/services.py", line 82, in async_handle_start_charge
await coordinator.async_start_charge(vehicle_id)
File "/config/custom_components/kia_uvo/coordinator.py", line 127, in async_start_charge
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 112, in stop_charge
return self.api.stop_charge(self.token, self.get_vehicle(vehicle_id))
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 485, in stop_charge
headers["pAuth"] = self._get_pin_token(token, vehicle.id)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 333, in _get_pin_token
headers["vehicleId"] = vehicle.id
AttributeError: 'str' object has no attribute 'id'

**Comment by cdnninja** [comment]
This next one is solved in 2.0.3. I think we are getting close.

**Comment by zadigre** [comment]
there is no more error. 

but start charge does not work... I have this popup on my phone when trying the start charge. 
![IMG_3111](https://user-images.githubusercontent.com/4810599/198900332-d85a7728-832d-47f5-a4e4-12b3778ae3d5.jpeg)
It's working fine if I start the charge directly on my phone.

stop charge works fine... it stops the charge that was started through the app. 

I tried to find which command is sent to the Bluelink/car when starting a charge from Edge browser... 
I can see a vrfypin (https://mybluelink.ca/tods/api/vrfypin), rcstrt (https://mybluelink.ca/tods/api/evc/rcstrt) and also rmtsts (https://mybluelink.ca/tods/api/rmtsts) just before it starts charging. 

which information would you need exactly to get this fixed?

**Comment by zadigre** [comment]
fyi, for the rcstrt on the web, payload is my pin... exact same as the vrfypin. 
so it looks like pin is sent twice on the web. 

I do get this in the log following a start charge command
2022-10-30 18:35:31.494 DEBUG (SyncWorker_5) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received start_charge response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}}

but there's no current drawn from my charging station... and the error popup on my iPhone.

**Comment by cdnninja** [comment]
Hmm this code is virtually unchanged from the old version. Did this work in 1.X?

**Comment by zadigre** [comment]
I've used it last winter... 
I have an automation that sends a stop charge at 6am when there's a high usage period announced by Hydro Québec. 
I use the stop charge more often... but I've tested my automation and both start and stop were working fine. 

payload for both start and stop are the same (my pin). 

headers too looks the same.

anything else I can do to fin what is going on?

headers for both:
		URL de la demande: https://mybluelink.ca/tods/api/evc/rcstrt
		Méthode de demande: POST
		 Code d’état: 200 OK
		Adresse distante: 209.136.139.219:443
		Stratégie de référent: strict-origin-when-cross-origin
		En-têtes de réponseAfficher la source
		Access-Control-Allow-Credentials: true
		Access-Control-Allow-Headers: language, offset, UCID, From, x-requested-with, Content-Type, origin, authorization, accept, client-security-token, accesstoken, clientId, clientSecret
		Access-Control-Allow-Headers: x-requested-with
		Access-Control-Allow-Methods: POST, GET
		Access-Control-Allow-Methods: POST, GET
		Access-Control-Allow-Origin: *
		Access-Control-Expose-Headers: transactionId, transactionDate, offset, language
		Access-Control-Max-Age: 1000
		Access-Control-Max-Age: 3600
		Connection: Keep-Alive
		Content-Language: en
		Content-Type: application/json;charset=UTF-8
		Date: Mon, 31 Oct 2022 01:33:05 GMT
		Keep-Alive: timeout=3, max=149
		language: 0
		offset: -8
		Server: Oracle-Application-Server-11g
		Server-Timing: dtRpid;desc="-1509216671"
		Timing-Allow-Origin: *
		transactionDate: Mon, 31 Oct 2022 01:33:05 GMT
		transactionId: 142606798
		Transfer-Encoding: chunked
		X-Powered-By: Servlet/2.5 JSP/2.1
		En-têtes de demandeAfficher la source
		Accept: application/json, text/plain, */*
		Accept-Encoding: gzip, deflate, br
		Accept-Language: fr-CA,fr;q=0.9,fr-FR;q=0.8,en-CA;q=0.7,en;q=0.6,en-US;q=0.5,en-GB;q=0.4
		accessToken: @@@@@token here@@@@
		Connection: keep-alive
		Content-Length: 14
		content-type: application/json;charset=UTF-8
		Cookie: @@@@cookie here@@@@
		from: CWP
		Host: mybluelink.ca
		language: 0
		offset: -4
		Origin: https://mybluelink.ca
		pAuth: @@@@pAuth here@@@@
		Referer: https://mybluelink.ca/remote/charge
		sec-ch-ua: "Microsoft Edge";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
		sec-ch-ua-mobile: ?0
		sec-ch-ua-platform: "macOS"
		Sec-Fetch-Dest: empty
		Sec-Fetch-Mode: cors
		Sec-Fetch-Site: same-origin
		User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.24
		vehicleId: @@@@vehiculeid here@@@@



		URL de la demande: https://mybluelink.ca/tods/api/evc/rcstp
		Méthode de demande: POST
		Code d’état: 200 OK
		Adresse distante: 209.136.139.219:443
		Stratégie de référent: strict-origin-when-cross-origin
		En-têtes de réponseAfficher la source
		Access-Control-Allow-Credentials: true
		Access-Control-Allow-Headers: language, offset, UCID, From, x-requested-with, Content-Type, origin, authorization, accept, client-security-token, accesstoken, clientId, clientSecret
		Access-Control-Allow-Headers: x-requested-with
		 Access-Control-Allow-Methods: POST, GET
		Access-Control-Allow-Methods: POST, GET
		Access-Control-Allow-Origin: *
		Access-Control-Expose-Headers: transactionId, transactionDate, offset, language
		Access-Control-Max-Age: 1000
		Access-Control-Max-Age: 3600
		Connection: Keep-Alive
		Content-Language: en
		Content-Type: application/json;charset=UTF-8
		Date: Mon, 31 Oct 2022 01:33:53 GMT
		Keep-Alive: timeout=5, max=149
		language: 0
		offset: -8
		Server: Oracle-Application-Server-11g
		Server-Timing: dtRpid;desc="-482596107"
		Timing-Allow-Origin: *
		transactionDate: Mon, 31 Oct 2022 01:33:53 GMT
		transactionId: 142608303
		Transfer-Encoding: chunked
		X-Powered-By: Servlet/2.5 JSP/2.1
		En-têtes de demandeAfficher la source
		Accept: application/json, text/plain, */*
		Accept-Encoding: gzip, deflate, br
		Accept-Language: fr-CA,fr;q=0.9,fr-FR;q=0.8,en-CA;q=0.7,en;q=0.6,en-US;q=0.5,en-GB;q=0.4
		accessToken: @@@@@token here@@@@
		Connection: keep-alive
		Content-Length: 14
		content-type: application/json;charset=UTF-8
		Cookie: @@@@cookie here@@@@
		from: CWP
		Host: mybluelink.ca
		language: 0
		offset: -4
		Origin: https://mybluelink.ca
		pAuth: @@@@pAuth here@@@@
		Referer: https://mybluelink.ca/remote/charge
		sec-ch-ua: "Microsoft Edge";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
		sec-ch-ua-mobile: ?0
		sec-ch-ua-platform: "macOS"
		Sec-Fetch-Dest: empty
		Sec-Fetch-Mode: cors
		Sec-Fetch-Site: same-origin
		User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.24
		vehicleId: @@@@vehiculeid here@@@@

**Comment by cdnninja** [comment]
I will do some more line by line comparison soon to what you post.  You have me somewhat stumped.   Something must be off in our payload though.  

To confirm you are testing this via the gui in the developer tab and not via any existing automation or dashboard?

**Comment by zadigre** [comment]
I test both the gui and my existing automatisions/script. 
when something is not working in my scripts or automations, I always go to the developer menu to test and confirm my existing settings and adjust accidentally if needed.
In this case, I went straight to the dev menu gui for all my tests.

**Comment by zadigre** [comment]
2.0.10 didn't fix this problem...
but I have some more information. 

even it if fails, it does send something to the car. 
I have a charging schedule enabled which makes the car start charging only when it's time to charge to be ready by 7am. But when starting the charge manually through the app or web portal, it starts immediately.
When I send the start charge command through HA, the charging schedule light shuts off, I hear my charging station "click" like it does when it starts charging and it stops immediately... and then I receive the pop error message on my app. 
I tried 3 times to make sure I was getting the same result. Between every tries, I unplug my car and plug it back to make sure connection was ok. 
I then tried with MyHyundai app... and it worked immediately. It also works immediately if I start through the web portal. 

I don't see my pin for the start charge command like I see it for climate. is it normal? it's not supposed to be included somewhere in the payload?

Here's the log:
2022-11-02 18:59:07.606 DEBUG (SyncWorker_6) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Pin Headers {'content-type': 'application/json;charset=UTF-8', 'accept': 'application/json, text/plain, */*', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36', 'host': 'mybluelink.ca', 'origin': 'https://mybluelink.ca', 'referer': 'https://mybluelink.ca/login', 'from': 'SPA', 'language': '0', 'offset': '0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-origin', 'accessToken': '****access token here****', 'pAuth': '***pAuth here***'}
2022-11-02 18:59:08.218 DEBUG (SyncWorker_6) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received Pin validation response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'pAuth': '***pAuth here***'}}
2022-11-02 18:59:09.563 DEBUG (SyncWorker_6) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received start_charge response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}}

**Comment by cdnninja** [comment]
Today we don't log the headers in start_charge but pin is in the code.  Here is the link: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/2b1331d964c3198ed8e0239fc4b28141955216d4/hyundai_kia_connect_api/KiaUvoApiCA.py#L474-L488

You are going down the exact right path though. I actually remember this issue before with clicking and it was something with our payload being a tiny bit off.  I will search issues to see if I can find it.

**Comment by cdnninja** [comment]
Could you do me a favor and roll back to 1.8.X to confirm this still works? I think you will need to remove the integration and reconfigure it after.  I am wondering if this is a change on the Hyundai side.  If so it changes my focus. 

I am thinking detail comparison of the payloads next to a working payload  will need to be done to find this issue.

**Comment by zadigre** [comment]
I'll install a plain HA in virtual box to test it... I don't want to touch my ok working main HA server now 😉 I'll let you know when done.

**Comment by zadigre** [comment]
installed and tested... start and stop charge works fine in 1.8.2.

**Comment by cdnninja** [comment]
Okay that is great to know.  So now we need to get detailed logs from both.   What we need is both logged headers and payload from the working and none working so we can show side by side what is different.    I don't see any differences from the code by my eyes must be missing something.  I may need to add some more debug logging, I will need to look.

**Comment by cdnninja** [comment]
Confirmed I will need to add debug. I will release an update for both versions with extensive logging and then we can compare the payload and headers.

**Comment by cdnninja** [comment]
I have added logging to the latest builds of both 1.8.X and 2.0.X that match.  The logging is for start charge only.  It should dump headers and the pin from the body.  In theory these logs should match almost identically with just things like access token being different.

**Comment by zadigre** [comment]
I see 2.0.13 available but latest in 1.8.x is 1.8.2

**Comment by cdnninja** [comment]
Ran a release so 1.8.3 is out.

**Comment by zadigre** [comment]
2.0.13 start_charge that fails:
2022-11-03 20:56:40.583 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Pin Headers {'content-type': 'application/json;charset=UTF-8', 'accept': 'application/json, text/plain, */*', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36', 'host': 'mybluelink.ca', 'origin': 'https://mybluelink.ca', 'referer': 'https://mybluelink.ca/login', 'from': 'SPA', 'language': '0', 'offset': '0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-origin', 'accessToken': '****accesss token here***=', 'vehicleId': 'qLHNk/TY2fGJeLL1FVGDXA==', 'pAuth': 'HZQlLUvSHbGBTJuFJmBoAycHXOPRMYmE'}
2022-11-03 20:56:41.132 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received Pin validation response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'pAuth': 'nlzBFBonAVchvDbsfzzwRnioqUWQIoRT'}}
2022-11-03 20:56:42.092 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received start_charge response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}}



1.8.3 that works fine:
2022-11-03 20:58:38.194 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received Pin validation response <Response [200]>
2022-11-03 20:58:38.194 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Planned start_charge headers {'content-type': 'application/json;charset=UTF-8', 'accept': 'application/json, text/plain, */*', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36', 'host': 'www.mybluelink.ca', 'origin': 'https://www.mybluelink.ca', 'referer': 'https://www.mybluelink.ca/login', 'from': 'SPA', 'language': '0', 'offset': '0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-origin', 'accessToken': '***access token here***=', 'vehicleId': 'qLHNk/TY2fGJeLL1FVGDXA==', 'pAuth': 'sVqOsPvJYkhOQLFCJqSrSwiQGXFeAfYD'}
2022-11-03 20:58:38.194 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Planned start_charge payload {"pin": "****my pin here****"}
2022-11-03 20:58:38.849 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received start_charge response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}}

**Comment by cdnninja** [comment]
For the failing logs are you able to confirm that is complete?  Here is what the log commands are: 

`        _LOGGER.debug(f"{DOMAIN} - Planned start_charge headers {headers}")
        data=json.dumps({"pin": token.pin})
        _LOGGER.debug(f"{DOMAIN} - Planned start_charge payload {data}")`


The pin headers title you have is actually not either of these but rather a line ahead of them where it does pauth.  The odd part is it contains a pauth header which can't be true.

**Comment by zadigre** [comment]
I did a copy/past of everything that was present in the log right after doing the start charge command. 
I can try again later tonight with 2.0.15 to make sure it's indeed complete.

**Comment by zadigre** [comment]
here's the log with 2.0.15

2022-11-04 21:29:16.214 DEBUG (SyncWorker_3) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Pin Headers {'content-type': 'application/json;charset=UTF-8', 'accept': 'application/json, text/plain, */*', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36', 'host': 'mybluelink.ca', 'origin': 'https://mybluelink.ca', 'referer': 'https://mybluelink.ca/login', 'from': 'SPA', 'language': '0', 'offset': '0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-origin', 'accessToken': '*****accessToke here*****=', 'vehicleId': 'qLHNk/TY2fGJeLL1FVGDXA==', 'pAuth': 'rwrnztzkRHOmlMuXOMzHGZDqrGxjOndy'}
2022-11-04 21:29:16.922 DEBUG (SyncWorker_3) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received Pin validation response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'pAuth': 'YzPFGSBIvzvRpuUtdfCtVDZtVWaDPRFB'}}
2022-11-04 21:29:17.649 DEBUG (SyncWorker_3) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received start_charge response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}}

**Comment by cdnninja** [comment]
You have me stumped. It appears the above logs don't reflect the code unlike 1.8.X. I am wondering if the API isn't updating and you have an old version even though the integration itself is updating.  Any errors in your HA about hyundai_kia_connect_api?

**Comment by zadigre** [comment]
no error about connect_api.

only error is this one:
2022-11-07 19:15:57.302 WARNING (MainThread) [homeassistant.components.number] custom_components.kia_uvo.number::HyundaiKiaChargingLimitNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by zadigre** [comment]
here's the content of the kia_uno folder on my in /config/custom_components
https://www.icloud.com/iclouddrive/027MqAbJr9Qtk668jT4LCQI3g#kia_uvo
all files were updated at 15h41 when I installed the latest 2.0.x version. 

anything else I can check?

**Comment by cdnninja** [comment]
I can't open the link but those files should contain a manifest that shows the API version.  That file causes home assistant to download that version of the API and install it.  We will confirm if remote start resolves. If so API is updating correctly and logging isn't refreshing or something.  What platform are you running on?

**Comment by zadigre** [comment]
manifest.json:
{
  "domain": "kia_uvo",
  "name": "Kia Uvo / Hyundai Bluelink",
  "documentation": "https://github.com/fuatakgun/kia_uvo",
  "issue_tracker": "https://github.com/fuatakgun/kia_uvo/issues",
  "codeowners": ["@fuatakgun"],
  "requirements": ["hyundai_kia_connect_api==1.37.3"],
  "version": "2.0.19",
  "config_flow": true,
  "iot_class": "cloud_polling",
  "integration_type": "hub"


so it looks like it's updating. 

I'm running on home assistant OS running on an intel based small pc (similar to intel NUC).

**Comment by cdnninja** [comment]
Figured out why logging and hopefully it wasn't running.  both start and stop charge called stop charge.  Here is hoping both work for you now.

**Comment by zadigre** [comment]
great. I'll try to test it when I'm back from work tonight.
